global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'python_script'
    static_configs:
      - targets: ['host.docker.internal:8000']